---
- name: Setup database for web application
  hosts: localhost
  become: yes
  vars:
    db_name: "{{ db_name | default('webapp') }}"
    db_user: "{{ db_user | default('webapp') }}"
    db_password: "{{ db_password | default('changeme') }}"

  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql postgresql-contrib
        state: present
        update_cache: yes

    - name: Start and enable PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database
      postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create database user
      postgresql_user:
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "ALL"
        state: present

    - name: Grant privileges to user
      postgresql_privs:
        db: "{{ db_name }}"
        role: "{{ db_user }}"
        type: database
        privs: ALL
        state: present 